### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by abhishekrup** [frw/react-native-ssl-public-key-pinning#44] opened 2023-06-02 11:04 UTC
Hii, I created a new project and implemented SSL package and then when tried to test in android it is working in both condition with the wrong hashkey and also with right hashkey i am getting the status 301 also tested with includeSubdomains true and false 

Here is the code with the right hask key in google.com domain 
```
useEffect(() => {
    async function test() {
      try {
        await initializeSslPinning({
          'google.com': {
            includeSubdomains: true,
            publicKeyHashes: [
              'CLOmM1/OXvSPjw5UOYbAf9GKOxImEp9hhku9W90fHMk=',
              'hxqRlPTu1bMS/0DITB1SSu0vd4u/8l8TjPgfaAp63Gc=',
              'Vfd95BwDeSQo+NUYxVEEIlvkOlWY2SalKK1lPhzOx78=',
              'QXnt2YHvdHR3tJYmQIr0Paosp6t/nggsEGD4QJZ3Q0g=',
              'mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c=',
            ],
          },
          'clickit-eu-api-staging.herokuapp.com': {
            includeSubdomains: true,
            publicKeyHashes: [
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
              'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
            ],
          },
        });

        await fetch('https://google.com');
      } catch (e) {
        console.error(e);
      }
    }

    test();
  }, []);```

  Here is the code with wrong hashkey 
  ```useEffect(() => {
    async function test() {
      try {
        await initializeSslPinning({
          'google.com': {
            includeSubdomains: true,
            publicKeyHashes: [
               'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
              'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
            ],
          },
![Screenshot 2023-06-02 at 4 27 04 PM](https://github.com/frw/react-native-ssl-public-key-pinning/assets/134288913/6470fb7c-1dc6-424e-bba2-44def72fa9da)

          'clickit-eu-api-staging.herokuapp.com': {
            includeSubdomains: true,
            publicKeyHashes: [
              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
              'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
            ],
          },
        });

        await fetch('https://google.com');
      } catch (e) {
        console.error(e);
      }
    }
    test();
  }, []);```
  
  You will get the status 301 in response i am adding the screenshot below:-
  
![Screenshot 2023-06-02 at 4 27 04 PM](https://github.com/frw/react-native-ssl-public-key-pinning/assets/134288913/cf1cb3dc-a68c-4e9d-81ca-a5995d8eff99)

**Comment by abhishekrup** [comment] 2023-06-05 05:02
I have created a fresh new project with react "react-native": "0.71.8" and "react-native-ssl-public-key-pinning": "^1.0.5"  and i have added the upper code in app.js and the i tested the google.com with right hashkey and wrong hashkey but in response i am getting the same status code 301 in both cases can you please test like that way then you might be able to reproduce the issue and can provide me the proper solution

**Comment by abhishekrup** [comment] 2023-06-05 12:59
```import * as React from 'react';

import {
  StyleSheet,
  View,
  Text,
  TextInput,
  Button,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
} from 'react-native';
import {
  disableSslPinning,
  initializeSslPinning,
  isSslPinningAvailable,
} from 'react-native-ssl-public-key-pinning';

const GOOGLE_DOMAIN = 'clickit-eu-api.herokuapp.com';

// Google Trust Services https://pki.goog/repository/
const GTS_HASHES = [
  '7LH5DTxeQe8VmSch3vRaANS6DfCmflmtKyRoIh2aIQI=', //This is right hash key for domain clickit-eu-api.herokuapp.com but not working properly
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
].join('\n');

// Let's Encrypt https://letsencrypt.org/certificates/
const LE_HASHES = [
  'C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=', // ISRG Root X1
  'diGVwiVYbubAI3RW4hB9xU8e/CH2GnkuvVFZE8zmgzI=', // ISRG Root X2
].join('\n');

const DOMAIN_PLACEHOLDER = 'clickit-eu-api.herokuapp.com';
const PUBLIC_KEY_HASHES_PLACEHOLDER = [
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
].join('\n');

const App = () => {
  const [domain, setDomain] = React.useState('');
  const [publicKeyHashes, setPublicKeyHashes] = React.useState('');
  const [initializeResult, setInitializeResult] = React.useState('');

  const [testDomain, setTestDomain] = React.useState('');
  const [fetchResult, setFetchResult] = React.useState('');

  // React.useEffect(() => {
  //   async function test() {
  //     try {
  //       await initializeSslPinning({
  //         'google.com': {
  //           includeSubdomains: true,
  //           publicKeyHashes: [
  //              'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  //             'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
  //           ],
  //         },
  //         'clickit-eu-api.herokuapp.com': {
  //           includeSubdomains: true,
  //           publicKeyHashes: [
  //             'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  //             'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=',
  //           ],
  //         },
  //       });

  //       await fetch('https://clickit-eu-api.herokuapp.com');
  //     } catch (e) {
  //       console.error(e);
  //     }
  //   }
  //   test();
  // }, []);

  const onFillValid = React.useCallback(() => {
    setDomain(GOOGLE_DOMAIN);
    setPublicKeyHashes(GTS_HASHES);
    setTestDomain(GOOGLE_DOMAIN);
    setInitializeResult('');
    setFetchResult('');
  }, []);

  const onFillInvalid = React.useCallback(() => {
    setDomain(GOOGLE_DOMAIN);
    setPublicKeyHashes(LE_HASHES);
    setTestDomain(GOOGLE_DOMAIN);
    setInitializeResult('');
    setFetchResult('');
  }, []);

  const onInitializePinning = React.useCallback(async () => {
    console.log("domain",domain)
    try {
      await initializeSslPinning({
        [domain]: {
          includeSubdomains: true,
          publicKeyHashes: publicKeyHashes.trim().split('\n'),
        },
      });
      console.log('Inside ifff')
      setInitializeResult(`✅ Success Initializing`);
      setFetchResult('');
    } catch (e) {
      console.log('Inside eeeeee')
      setInitializeResult(`❌ ${e}`);
    }
  }, [domain, publicKeyHashes]);

  const onDisablePinning = React.useCallback(async () => {
    try {
      await disableSslPinning();
      setInitializeResult(`✅ Success Disabling`);
      setFetchResult('');
    } catch (e) {
      setInitializeResult(`❌ ${e}`);
    }
  }, []);

  const onFetch = React.useCallback(async () => {
    try {
      const response = await fetch(`https://${testDomain}`);
      console.log("response",response)
      setFetchResult(`${response.ok ? '✅' : '❌'} Status: ${response.status}`);
    } catch (e) {
      setFetchResult(`❌ ${e}`);
    }
  }, [testDomain]);

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      style={styles.root}
    >
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.container}
        keyboardShouldPersistTaps="handled"
        alwaysBounceVertical={false}
      >
        <Text testID="SslPinningAvailability" style={styles.availability}>
          SSL Pinning Available:{' '}
          <Text style={styles.availabilityStatus}>
            {isSslPinningAvailable() ? 'YES' : 'NO'}
          </Text>
        </Text>

        <View style={styles.divider} />

        <View style={styles.buttonContainer}>
          <View style={styles.button}>
            <Button
              testID="ValidExample"
              title="Valid Example"
              color="green"
              onPress={onFillValid}
            />
          </View>
          <View style={[styles.button, styles.componentMarginLeft]}>
            <Button
              testID="InvalidExample"
              title="Invalid Example"
              color="red"
              onPress={onFillInvalid}
            />
          </View>
        </View>

        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Domain:</Text>
          <TextInput
            style={styles.fieldInput}
            keyboardType="url"
            inputMode="url"
            placeholder={DOMAIN_PLACEHOLDER}
            placeholderTextColor="lightgray"
            value={domain}
            onChangeText={setDomain}
          />
        </View>

        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Public Key Hashes:</Text>
          <TextInput
            style={[styles.fieldInput, styles.fieldInputMultiline]}
            numberOfLines={3}
            multiline
            placeholder={PUBLIC_KEY_HASHES_PLACEHOLDER}
            placeholderTextColor="lightgray"
            value={publicKeyHashes}
            onChangeText={setPublicKeyHashes}
          />
        </View>

        <View style={styles.buttonContainer}>
          <View style={styles.button}>
            <Button
              testID="InitializePinning"
              title="Initialize Pinning"
              color="deepskyblue"
              onPress={onInitializePinning}
            />
          </View>
          <View style={[styles.button, styles.componentMarginLeft]}>
            <Button
              testID="DisablePinning"
              title="Disable Pinning"
              color="deepskyblue"
              onPress={onDisablePinning}
            />
          </View>
        </View>

        <Text testID="InitializeResultOutput" style={styles.result}>
          {initializeResult}
        </Text>

        <View style={styles.divider} />

        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Test:</Text>
          <View style={styles.testInputContainer}>
            <View style={styles.fetchDomainInput}>
              <TextInput
                testID="TestDomainInput"
                style={styles.fieldInput}
                keyboardType="url"
                inputMode="url"
                placeholder={DOMAIN_PLACEHOLDER}
                placeholderTextColor="lightgray"
                value={testDomain}
                onChangeText={setTestDomain}
              />
            </View>
            <View style={styles.componentMarginLeft}>
              <Button
                testID="TestFetch"
                title="Fetch"
                color="deepskyblue"
                onPress={onFetch}
              />
            </View>
          </View>
        </View>

        <Text testID="FetchResultOutput" style={styles.result}>
          {fetchResult}
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

export default App;

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  scrollView: {
    backgroundColor: 'darkslategray',
  },
  availability: {
    color: 'white',
  },
  availabilityStatus: {
    fontWeight: 'bold',
  },
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  field: {
    alignSelf: 'stretch',
    marginVertical: 8,
  },
  fieldLabel: {
    color: 'lightgray',
    fontWeight: 'bold',
  },
  fieldInput: {
    marginTop: 4,
    paddingVertical: 4,
    backgroundColor: 'white',
    color: 'black',
  },
  fieldInputMultiline: {
    textAlignVertical: 'top',
    height: 64,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginTop: 8,
  },
  button: {
    flex: 1,
  },
  testInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fetchDomainInput: {
    flexGrow: 1,
  },
  result: {
    textAlign: 'center',
    marginVertical: 8,
    color: 'white',
  },
  divider: {
    alignSelf: 'stretch',
    height: 1,
    backgroundColor: 'gray',
    marginVertical: 12,
  },
  componentMarginLeft: {
    marginLeft: 8,
  },
});
```
Here is my whole code

**Comment by frw** [comment] 2023-06-06 09:52
So I copied your code above into App.tsx in the example app (upgraded to RN 0.71.8), and after clicking on "Valid/Invalid Example" > "Initialize Pinning" > "Fetch", this is what I got:

|Valid Example|Invalid Example|
|--|--|
|![Screenshot_20230606-164822_SslPublicKeyPinningExample](https://github.com/frw/react-native-ssl-public-key-pinning/assets/1888212/def5f7bb-71bf-4638-aa0a-9f94e27af6ca)|![Screenshot_20230606-164532_SslPublicKeyPinningExample](https://github.com/frw/react-native-ssl-public-key-pinning/assets/1888212/9498575a-6d3e-4589-973b-85471002cd3d)|

So it seems to work as expected. I don't understand how you're getting a very different result here.
Could you create a new repository and upload all of the code with your setup for reproduction?

**Comment by frw** [comment] 2023-06-06 16:36
If you build and run the example app, does it work as expected though?

As I requested above, could you create a new repository and upload all of the code with your setup for reproduction? It might be due to a conflicting package. Also, what device are you using for testing?

**Comment by abhishekrup** [comment] 2023-06-07 05:13
Can you check the same code with the debug enable at that time i am getting the issue and in debug mode we are getting the same code 406 can you please test and let me know. Because i was testing in debug so i am getting 406 every time but after i disable the debug i am getting the response proper

**Comment by frw** [comment] 2023-06-07 05:55
> Can you check the same code with the debug enable at that time i am getting the issue and in debug mode we are getting the same code 406 can you please test and let me know. Because i was testing in debug so i am getting 406 every time but after i disable the debug i am getting the response proper

That's some good news. Could you clarify what you mean by enabling/disabling debug? Is this something you're setting on the RN side or in the Android build.gradle?

**Comment by abhishekrup** [comment] 2023-06-07 06:03
Yeah actually i got a strange thing i reinstalled the package in my new project and then when i enabled debug with chrome then i was getting 406 status in valid and invalid both but then i stopped the debug with chrome and then tested the app and it worked fine and now when i enable the debug then also it works i don't know how its a strange.I will implement the same code in my project and if it worked then i will close the issue.

Debugging involves thorough checking of the code and helps in the early detection of error conditions. Fixing these errors or bugs during the React Native app development process, instead of fixing them in the production stages can be highly economical for every company offering React Native app development services

**Comment by abhishekrup** [comment] 2023-06-07 08:51
"react-native": "0.64.2" me konsa version use kru react-native-ssl-public-key-pinning ka

**Comment by frw** [comment] 2023-06-07 14:51
> i stopped the debug with chrome and then tested the app and it worked fine
Ah that could indeed be why. If I'm not wrong when you use Remote JS Debugging, you're actually running the JS code on your development machine rather than on the mobile device (see the info panel on [here](https://reactnative.dev/docs/hermes)), so the `fetch` calls might have been resolved on Chrome's javascript engine rather than through the SSL pinned version on mobile. Unfortunately, it seems like you would have to keep Remote JS Debugging off in order to test the effects of SSL pinning, but at least you can be assured that it should work on the release version of your app.

> Which version of "react-native-ssl-public-key-pinning" should i use in "react-native": "0.64.2"
I haven't tested it on such an old RN version, but I believe the latest react-native-ssl-public-key-pinning version should work.

**Comment by frw** [comment] 2023-06-10 14:52
Closing since the issue seems to be with an older RN version and workarounds have been provided.
Let me know if you're still facing any issues!

**Closed by frw** 2023-06-10 14:52 UTC
Labels: repro-needed

**Comment by abhishekrup** [comment] 2023-06-12 04:24
Thanks its working with the workaround for older RN version
